export const JETTON_MINTER_ADDRESS = "EQCObh4-ZaghOva8uCz_AMMnvifM3PS-EppUJEJQXXnlP0zX";
export const STONFI_POOL_ADDRESS = "EQDMeSCkaJBWNTRdhumSIiZPCVuv5j7kxcJjYno9-Y5hTPJS";
export const DEDUST_POOL_ADDRESS = "UQDyE1UTlNajj1sJQAiI7o0spIIERH_iuYWRW33PWp1-tf4T";